name: Main

on:
  pull_request:
    branches: [ "main" ]

jobs:
  client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        working-directory: ./client
        run: npm i
      - name: Lint
        working-directory: ./client
        run: npm run lint
      - name: Build
        working-directory: ./client
        run: npm run build
  server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      working-directory: ./server
      run: npm i
    - name: ESLint
      working-directory: ./server
      run: npm run lint
